# Generated by Django 4.1 on 2022-09-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_order_contacts'),
        ('core', '0004_bottlescount_count_bottlescount_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='bottles', to='clients.order', verbose_name='Orders'),
        ),
    ]
