# Generated by Django 4.1 on 2022-09-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_order_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contacts',
            field=models.CharField(blank=True, help_text='Phone number or telegram', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Enter your full name', max_length=255),
        ),
    ]
